- hosts: pi
  gather_facts: no
  vars:
    numbers: [3, 2, 1, 3, 2]
    path: /var/log/upstart/nginx.log

  tasks:
    - name: get min number
      ansible.builtin.debug: msg={{ numbers | min }}
    - name: get max number
      ansible.builtin.debug: msg={{ numbers | max }}
    - name: get unique values
      ansible.builtin.debug: var={{ item }}
      loop: "{{ numbers | unique }}"
    - name: get random value
      ansible.builtin.debug: msg={{ ['a', 'b', 'c'] | random }}

    - ansible.builtin.debug: msg={{ '192.0.2.1/24' | ipaddr('address') }}
    - ansible.builtin.debug: msg={{ 'test1' | hash('sha1') }}
    - ansible.builtin.debug: msg={{ path | basename }}
    - ansible.builtin.debug: msg={{ path | dirname }}
    - ansible.builtin.debug: msg={{ "~/Movies" | expanduser }}
