- hosts: ocean
  tasks:
    - name: install git
      # apt-get update && apt-get install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      become: yes
