- hosts: localhost

  vars:
    base_config_path: /tmp/.env
    confd_path: /tmp/env.d
    root_path: "/opt/"

  tasks:
    # BEGIN (write your solution here)

    
    # END

    - name: Retrieve file system status
      stat:
        path: "{{ item }}"
        get_md5: false
        get_checksum: false
        get_attributes: false
        get_mime: false
      with_items:
        - "{{ confd_path }}"
        - "{{ confd_path }}/base_config"
        - "{{ base_config_path }}"
      register: results

    - name: Check all files and dirs exists
      fail:
        msg: "Expected {{ item.item }} to be exists"
      when: not item.stat.exists
      with_items: "{{ results.results }}"

    - name: Check configs
      lineinfile:
        dest: "{{ base_config_path }}"
        line: "{{item}}"
      check_mode: yes
      register: presence
      failed_when: presence.changed
      with_items:
        - "CPU_NUMBERS={{ ansible_processor_cores }}"
        - "HOSTNAME={{ ansible_hostname }}"
        - "IP_ADDRESS={{ ansible_all_ipv4_addresses[0] }}"

    - name: Check configs for one core machine
      lineinfile:
        dest: "{{ base_config_path }}"
        line: "{{item}}"
      check_mode: yes
      register: presence
      failed_when: presence.changed
      with_items:
        - USE_THREADS=0
      when: ansible_processor_cores == 1
